kind: Service
apiVersion: v1
metadata:
  name: test10
  namespace: test
spec:
  selector:
    app: test10
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    name: http
